### ISSUE TITLE
Problem starting

### ISSUE THREAD

**Issue by KukazMontero-s** [inria-muse/service-traceroute#2]
Hello I have kali linux and the following problem occurs when I try to start service traceroute
![image](https://user-images.githubusercontent.com/75347988/152031667-71b71c01-df60-4e69-b959-4444e852d90d.png)

**Comment by wontoniii** [comment]
Hello,
You have to specify the interface to use for service-traceroute to work: https://github.com/inria-muse/service-traceroute/blob/master/cmd/servicetraceroute/servicetraceroute.go#L32

**Comment by KukazMontero-s** [comment]
specify a file or in the command at startup ?, if so, how is it specified in the ?

**Comment by wontoniii** [comment]
You should try the `-h` option to see how to run the program.

**Comment by KukazMontero-s** [comment]
It is not clear to me how to enter the interface,
"./build/servicetraceroute-linux-amd64 -start eth0" or "./build/servicetraceroute-linux-amd64 -start -eth0", "./build/servicetraceroute-linux-amd64 --hosts eth" do not work
